# Generated by Django 4.2.16 on 2024-11-07 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_load_initial_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_caja', models.BooleanField(default=False)),
                ('fecha_hs_aper_caja', models.DateTimeField()),
                ('fecha_hs_cierre_caja', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial_caja', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_saldo_caja', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
