# Generated by Django 4.2.16 on 2024-11-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_caja'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
