# Generated by Django 4.2.16 on 2024-11-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_producto_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='producto',
            name='type_prod',
            field=models.CharField(default='', max_length=100),
        ),
    ]
