# Generated by Django 4.2.16 on 2024-11-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_category_producto_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='estado_pedido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='facturacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='producto',
            name='pago',
            field=models.CharField(default='', max_length=100),
        ),
    ]
