# Generated by Django 5.1.2 on 2024-11-22 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_producto_category_producto_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='estado_pedido',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='facturacion',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='pago',
            field=models.CharField(default='', max_length=100),
        ),
    ]
