# Generated by Django 4.2.16 on 2024-11-25 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_venta_estado_pedido_venta_facturacion_venta_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='nombre_venta',
            field=models.CharField(default='', max_length=100),
        ),
    ]
