# Generated by Django 4.2.16 on 2024-11-25 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_venta_nombre_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='usuario_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apertura_cajas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierre_cajas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venta',
            name='caja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='api.caja'),
        ),
    ]
