# Generated by Django 4.2.16 on 2024-11-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_caja_usuario_apertura_caja_usuario_cierre_venta_caja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='caja',
        ),
        migrations.AddField(
            model_name='venta',
            name='caja_id',
            field=models.IntegerField(null=True),
        ),
    ]
