# Generated by Django 4.2.16 on 2024-11-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_venta_caja_venta_caja_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='total_ventas',
            field=models.IntegerField(null=True),
        ),
    ]
