# Generated by Django 4.2.16 on 2024-11-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_venta_total_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_ventas',
        ),
        migrations.AddField(
            model_name='caja',
            name='total_ventas',
            field=models.IntegerField(null=True),
        ),
    ]
