# Generated by Django 4.2.16 on 2024-11-26 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_venta_total_ventas_caja_total_ventas'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='nombre',
            field=models.CharField(default='', max_length=500),
        ),
    ]
