# Generated by Django 4.2.16 on 2024-11-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_caja_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='code_order',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
