# Generated by Django 5.1.2 on 2024-11-29 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_caja_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='codeOrder',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='venta',
            name='tipoPago',
            field=models.CharField(default='', max_length=100),
        ),
    ]
