# Generated by Django 4.2.16 on 2024-11-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_venta_code_order_venta_tipo_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='total_ventas_tarjetas',
            field=models.IntegerField(null=True),
        ),
    ]
