# Generated by Django 4.2.16 on 2024-11-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_caja_total_ventas_tarjetas'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='total_ventas_efectivo',
            field=models.IntegerField(null=True),
        ),
    ]
