version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: brunette_db
      POSTGRES_USER: brunette
      POSTGRES_PASSWORD: 1234
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: brunette_db
      DB_USER: brunette
      DB_PASS: 1234
    command: >
      sh -c "if [ ! -f ./manage.py ]; then 
                django-admin startproject api . && python manage.py migrate && python manage.py runserver 0.0.0.0:8000;
             else 
                python manage.py migrate && python manage.py runserver 0.0.0.0:8000;
             fi"

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    command: >
      sh -c "npm start"

volumes:
  postgres_data:
